runtime: php83

entrypoint: serve index.php

env_variables:
  DB_USER: cs4750-research-page
  DB_PASS: researchDB_25
  DB_NAME: research_info
  INSTANCE_CONNECTION_NAME: cs4750-db-group:us-east4:cs4750-research-page
